name: Automated Unit Testing
on: 
  pull_request:
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
      TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_WRONG_EMAIL : ${{ secrets.TEST_WRONG_EMAIL}}
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install all dependencies
        run: npm install

      - name: Run Tests
        run: npm run test-unit